#!/bin/bash

LINK_CMD="ln -sfn"
CWD=$(pwd)


#============== VIM SETUP ==========================

$LINK_CMD $CWD/.vimrc ~/.vimrc
$LINK_CMD $CWD/.vim ~/.vim
$LINK_CMD $CWD/.config/nvim ~/.config/nvim

nvim --headless +PlugInstall +qall
nvim --headless +CocInstall coc-pyright coc-tsserver coc-eslint coc-prettier +qall
nvim --headless +CocUpdate +qall

#============== END VIM SETUP =======================


#============== TMUX SETUP ==========================

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
$LINK_CMD $CWD/.tmux.conf ~/.tmux.conf
$LINK_CMD $CWD/.tmux ~/.tmux
~/.tmux/plugins/tpm/scripts/install_plugins.sh

#============== END TMUX SETUP ======================

