#!/bin/zsh

LINK_CMD=(ln -sfn)
CWD=$(pwd)

#============== ZSH SETUP =============================

chsh -s /bin/zsh
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

cd $ZPREZTODIR
git clone --recurse-submodules https://github.com/belak/prezto-contrib contrib

sh -c "$(curl -fsSL https://starship.rs/install.sh)"
$LINK_CMD $CWD/.zshrc ~/.zshrc
#============== END ZSH SETUP ==========================


#============== VIM SETUP ==========================

$LINK_CMD $CWD/.vimrc ~/.vimrc
$LINK_CMD $CWD/.vim ~/.vim
$LINK_CMD $CWD/.config/nvim ~/.config/nvim

nvim --headless +PlugInstall +qall
nvim --headless +CocInstall coc-pyright coc-tsserver coc-eslint coc-prettier +qall
nvim --headless +CocUpdate +qall

#============== END VIM SETUP =======================


#============== TMUX SETUP ==========================

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
$LINK_CMD $CWD/.tmux.conf ~/.tmux.conf
$LINK_CMD $CWD/.tmux ~/.tmux
~/.tmux/plugins/tpm/scripts/install_plugins.sh

#============== END TMUX SETUP ======================

